---
- name: Install the latest version of postfix
  dnf:
    name: postfix
    state: latest

- name: Install the latest version of alpine
  dnf:
    name: alpine
    state: latest

- name: Install the latest version of dovecot
  dnf:
    name: dovecot
    state: latest

- name: Install the latest version of telnet
  dnf:
    name: telnet
    state: latest

- name: Install the latest version of epel-release
  dnf:
    name: epel-release
    state: latest

- name: Install the latest version of dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Install the latest version of make
  dnf:
    name: make
    state: latest

- name: Install the latest version of ImageMagick
  dnf:
    name: ImageMagick
    state: latest

- name: Install the latest version of ImageMagick-devel
  dnf:
    name: ImageMagick-devel
    state: latest

- name: Install the latest version of ImageMagick-perl
  dnf:
    name: ImageMagick-perl
    state: latest

- name: Install the latest version of pcre-devel
  dnf:
    name: pcre-devel
    state: latest

- name: Install the latest version of zlib
  dnf:
    name: zlib
    state: latest

- name: Install the latest version of zlib-devel
  dnf:
    name: zlib-devel
    state: latest

- name: Install the latest version of libzip
  dnf:
    name: libzip
    state: latest

- name: Install the latest version of libzip-devel
  dnf:
    name: libzip-devel
    state: latest

- name: Install the latest version of libmcrypt-devel
  dnf:
    name: libmcrypt-devel
    state: latest

- name: Install the latest version of php
  dnf:
    name: php
    state: latest

- name: Install the latest version of php-fpm
  dnf:
    name: php-fpm
    state: latest

- name: Install the latest version of php-devel
  dnf:
    name: php-devel
    state: latest

- name: Install the latest version of php-pear
  dnf:
    name: php-pear
    state: latest

- name: Install the latest version of php-cli
  dnf:
    name: php-cli
    state: latest

- name: Install the latest version of php-gd
  dnf:
    name: php-gd
    state: latest

- name: Install the latest version of php-curl
  dnf:
    name: php-curl
    state: latest

- name: Install the latest version of php-xml
  dnf:
    name: php-xml
    state: latest

- name: Install the latest version of php-mysqlnd
  dnf:
    name: php-mysqlnd
    state: latest

- name: Install the latest version of php-mbstring
  dnf:
    name: php-mbstring
    state: latest

- name: Install the latest version of php-intl
  dnf:
    name: php-intl
    state: latest

- name: Install the latest version of php-ldap
  dnf:
    name: php-ldap
    state: latest

- name: Install the latest version of mariadb
  dnf:
    name: mariadb
    state: latest

- name: Install the latest version of mariadb-server
  dnf:
    name: mariadb-server
    state: latest

- name: Install the latest version of imagick
  community.general.pear:
    name: pecl/imagick
    state: latest

- name: Install the latest version of mcrypt
  community.general.pear:
    name: pecl/mcrypt
    state: latest

- name: Install the latest version of zip
  community.general.pear:
    name: pecl/zip
    state: latest

- name: overwrite main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix service

- name: Add mailuser
  user:
    name: mailuser
    state: present
    password: "{{ email_password|password_hash('sha256') }}"

- name: Email nagios@scoring.sa.cs.ut.ee
  become_user: mailuser
  shell:
    cmd: "echo -e 'Subject: You Should Hire Bill! \n\nYou should hire Bill at HPC! \nThis e-mail was sent by mailuser using the sendmail command in Bill's custom-made Postfix installation using his badass Ansible playbook. Hugs and kisses from {{ hostname }}@{{ domain_name }}!' | sendmail {{ email_recipient }}"

- name: update 10-logging.conf
  copy:
    src: 10-logging.conf
    dest: /etc/dovecot/conf.d/10-logging.conf
    owner: root
    group: root
    mode: '0644'

- name: update dovecot.conf
  copy:
    src: dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'

- name: update 10-auth.conf
  copy:
    src: 10-auth.conf
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: '0644'

- name: update 10-mail.conf 
  copy:
    src: 10-mail.conf
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'

- name: update 15-mailboxes.conf
  copy:
    src: 15-mailboxes.conf
    dest: /etc/dovecot/conf.d/15-mailboxes.conf
    owner: root
    group: root
    mode: '0644'    

- name: update 10-master.conf
  copy:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: '0644'
    
- name: update 10-ssl.conf
  copy:
    src: 10-ssl.conf
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: '0644'