---
- name: Restart named service
  service: 
    name: named
    state: restarted
    enabled: yes

- name: Reload firewalld service
  systemd: 
    name: firewalld
    state: reloaded
    enabled: yes
    # permanent: yes

- name: increment serial
  shell: 
    cmd: awk -i inplace '{if ($0 ~ /Serial/) $1 = $1 + 1; print}' /etc/named/{{ hostname }}.{{ domain_name }}

- name: Restart httpd service
  service: 
    name: httpd
    state: restarted
    enabled: yes