---
- hosts: all
  user: centos
  become: yes
  become_user: root
  vars:
    hostname: B98041Bill
    domain_name: sa.cs.ut.ee
    ip_address: 172.17.88.112
    zone_serial: 0531202203
    reverse_ip: 88.17.172
    scoring_server: 172.17.66.134

  roles:
  - { role: ports, tags: ports }
  - { role: services, tags: services }  
  # - { role: 02-etais, tags: etais }
  - { role: 04-dns, tags: dns }
  - { role: 05-web-apache, tags: web-apache }
  - { role: 06-email-smtp-imap, tags: email-smtp-imap }
  - { role: 07-tls, tags: tls }
  - { role: 08-filesystems, tags: filesystems }
  - { role: 09-containers, tags: containers }
  - { role: 10-devops, tags: DevOps }
  - { role: 11-k8s, tags: Kubernetes }
    #- tier1

  tasks:
  # - name: Testing this bitch out
  #   debug: msg="Ansible is a savior and a bitch at the same time. I am {{ ansible_user_id }} on server {{ ansible_hostname }}"
