---
# - name: Reload the named service in DNS
#   systemd:
#     name: named
#     state: reloaded
#     enabled: yes

- name: Restart named service
  systemd:
    name: named
    state: restarted
    enabled: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes    

- name: reload postfix
  systemd:
    named: postfix
    state: reloaded
    enabled: yes

- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted
    enabled: yes