---
- name: DNS | Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Get OpenStack metadata
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    method: GET
    status_code: 200
    return_content: yes
  register: cloud_metadata

- name: Print IP address
  debug: var=cloud_metadata.content  

- name: Disable IPv6
  copy: 
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Inserts into hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Inserts into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Install the latest version of bind
  yum:
    name: bind
    state: latest

- name: Install the latest version of bind-utils
  yum:
    name: bind-utils
    state: latest    

- name: Inserts into resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload the named service in dns

- name: Create DNS zone file
  template:
    src: zone_file.j2 
    dest: "/etc/named/{{ hostname }}.{{ domain_name }}"
    owner: named
    group: named
    mode: '0640'
  notify:
    - restart named

- name: Create reverse mapping zone file
  template:
    src: reverse_zone.j2 
    dest: "/etc/named/{{ reverse_zone }}.{{ domain_name }}"
    owner: named
    group: named
    mode: '0640'
  notify:
    - restart named    
