---
- name: DNS | Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

# - name: pause
#   pause:
#     prompt: "Press [Enter] to continue..."

- name: add DNS service
  ansible.posix.firewalld:
    service: dns
    permanent: yes
    state: enabled

- name: Get OpenStack metadata
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    method: GET
    status_code: 200
    return_content: yes
  register: cloud_metadata

- name: Print IP address
  debug: var=cloud_metadata.content

- name: open port 53/TCP for DNS
  ansible.posix.firewalld:
    port: 53/tcp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: open port 53/UDP for DNS
  ansible.posix.firewalld:
    port: 53/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: open port 8301/TCP for Scoring
  ansible.posix.firewalld:
    port: 8301/tcp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: open port 8301/UDP for Scoring
  ansible.posix.firewalld:
    port: 8301/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

# - name: reload firewalld
#   systemd:
#     name: firewalld
#     state: reloaded
#     enabled: yes

- name: Disable IPv6
  copy: 
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Inserts into hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Inserts into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  notify:
    Reboot a slow machine that might have lots of updates to apply    

- name: Install the latest version of bind
  yum:
    name: bind
    state: latest

- name: Install the latest version of bind-utils
  yum:
    name: bind-utils
    state: latest

- name: Create log directory
  file:
    path: /var/named/log
    state: directory
    owner: named
    group: named
    mode: '0700'

- name: Create default in log directory
  file:
    path: /var/named/log/default
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Create auth_servers in log directory
  file:
    path: /var/named/log/auth_servers
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Create zone_transfers in log directory
  file:
    path: /var/named/log/zone_transfers
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Create client_security in log directory
  file:
    path: /var/named/log/client_security
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Create queries in log directory
  file:
    path: /var/named/log/queries
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Create query-errors in log directory
  file:
    path: /var/named/log/query-errors
    state: touch
    owner: named
    group: named
    mode: '0640'

- name: Inserts into resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart named service

- name: Create DNS zone file
  template:
    src: zone_file.j2 
    dest: "/etc/named/{{ hostname }}.{{ domain_name }}"
    owner: root
    group: named
    mode: '0644'
  notify:
    - Restart named service
    - Increment serial

- name: Create reverse mapping zone file
  template:
    src: reverse_zone.j2 
    dest: "/etc/named/reverse.{{ hostname }}.{{ domain_name }}"
    owner: named
    group: named
    mode: '0644'
  notify:
    - Restart named service
    - Increment reverse mapping zone file serial

- name: Create named.conf
  template: 
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'
  notify:
    - Restart named service