---
# - name: Install the latest version of trivy
#   dnf:
#     name: trivy
#     state: latest

- name: Open port 58080/TCP for DNS
  ansible.posix.firewalld:
    port: 58080/tcp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Open port 58080/UDP for DNS
  ansible.posix.firewalld:
    port: 58080/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Open port 50080/TCP for DNS
  ansible.posix.firewalld:
    port: 50080/tcp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Open port 50080/UDP for DNS
  ansible.posix.firewalld:
    port: 50080/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Create /etc/traefik directory
  file:
    path: /etc/traefik
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy traefik.toml to the /etc/traefik directory
  copy: 
    src: traefik.toml
    dest: /etc/traefik
    owner: root
    group: root
    mode: '0755'

- name: Create traefik container 
  docker_container:
    name: traefik
    image: traefik:v2.1.8
    ports:
      - "50080:80"
      - "58080:8080"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: yes 
      - source: /etc/traefik/traefik.toml
        target: /traefik.toml
        type: bind
        read_only: yes
    restart_policy: always
    pull: yes 

- name: Create whoami-traefik container 
  docker_container:
    name: whoami-traefik
    image: registry.hpc.ut.ee/mirror/containous/whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.router.rule: 'Host(`{{ hostname }}.{{ domain_name }}`)'
      traefik.http.routers.router.entrypoints: web
    restart_policy: always
    pull: yes