---
# - name: Install the latest version of httpd
#   dnf:
#     name: httpd
#     state: latest

# - name: Install the latest version of python3-pip
#   dnf:
#     name: python3-pip
#     state: latest

# - name: Install the latest version of flask using PIP
#   pip:
#     name: flask

# - name: Install the latest version of php-mysqlnd
#   dnf:
#     name: php-mysqlnd
#     state: latest

# - name: Install the latest version of php-fpm
#   dnf:
#     name: php-fpm
#     state: latest

# - name: Install the latest version of mariadb-server
#   dnf:
#     name: mariadb-server
#     state: latest

# - name: Install the latest version of tar
#   dnf:
#     name: tar
#     state: latest

# - name: Install the latest version of curl
#   dnf:
#     name: curl
#     state: latest

# - name: Install the latest version of php-json
#   dnf:
#     name: php-json
#     state: latest    

# - name: Install the latest version of mod_security
#   dnf:
#     name: mod_security
#     state: latest

# - name: Install the latest version of netcat
#   dnf:
#     name: netcat
#     state: latest

- name: add HTTP service
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Create /var/www/ directory
  file:
    path: /var/www/
    state: directory
    owner: named
    group: named
    mode: '0700'

- name: Create /var/www/html/www.b98041/public_html/ directory
  file:
    path: /var/www/html/www.{{ hostname }}/public_html/
    state: directory
    owner: named
    group: named
    mode: '0700'

- name: Create Apache virtual host configuration file
  template:
    src: apache_virtual_host.j2 
    dest: /etc/httpd/conf.d/www.{{ hostname }}.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart named service

- name: remove all the content in welcome.conf
  copy:
    content: ''
    dest: /etc/httpd/conf.d/welcome.conf
    owner: root
    group: root
    mode: '0644'

- name: Create index.html
  template:
    src: index.j2 
    dest: /var/www/html/www.{{ hostname }}/public_html/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart httpd service

- name: useradd proxy
  user:
    name: proxy

- name: copy website.py
  copy:
    src: website.py
    dest: /usr/local/lib/server.py
    owner: proxy
    group: root 
    mode: '0644'

- name: create proxy.service
  template:
    src: proxy.service
    dest: /etc/systemd/system/proxy.service
    owner: root
    group: root
    mode: '0644'

- name: setsebool -P httpd_can_network_connect=1 proxy
  command: setsebool -P httpd_can_network_connect=1 proxy

- name: create virtual host for proxy 
  template:
    src: virtual_host_proxy.j2
    dest: /etc/httpd/conf.d/proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart httpd service